[versions]

# Plugins
agp = "8.5.2"
kotlin = "2.0.21"

# Android SDK
compileSdk = "35"
minSdk = "29"
targetSdk = "35"

# AndroidX
activity = "1.9.3"
appcompat = "1.7.0"
coreKtx = "1.15.0"
constraintLayout = "2.2.0"
recyclerview = "1.3.2"
lifecycleRuntimeKtx = "2.8.7"
lifecycleCommonJava8 = "2.8.7"
coroutines = "1.8.1"
datastorePreferences = "1.1.1"

# Material
material = "1.12.0"

# Testing
espressoCore = "3.6.1"
androidxJunit = "1.2.1"
junit = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
# Kotlin / Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

# Material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Testing
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
androidx = [
  "androidx-activity",
  "androidx-appcompat",
  "androidx-core-ktx",
  "androidx-constraintlayout",
  "androidx-recyclerview",
  "androidx-lifecycle-runtime-ktx",
  "androidx-lifecycle-common-java8",
  "androidx-datastore-preferences"
]
